# Generated by Django 2.2.5 on 2020-08-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155, verbose_name='Nome do curso')),
                ('titulo', models.CharField(choices=[('GRADUACAO', 'GRADUACAO'), ('MESTRADO', 'MESTRADO'), ('DOUTORADO', 'DOUTORADO')], max_length=10, verbose_name='TITULO')),
                ('instituicao', models.CharField(max_length=155, verbose_name='INSTITUICAO')),
                ('concluido', models.BooleanField(verbose_name='CONCLUIDO')),
                ('data_conclusao', models.CharField(max_length=50, verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crp', models.IntegerField(verbose_name='CRP')),
            ],
        ),
    ]
